(library
 (name garter_impl)
 (modules
  assembly
  compile
  compilehelpers
  wrapnatives
  naivestack
  freevars
  find
  errors
  exprs
  graph
  phases
  pretty
  registerallocation
  runner
  stringSet
  lexer
  parser
  cli
  types
  unify
  infer)
 (libraries ounit2 extlib unix str)
 (wrapped false))

(ocamllex
 (modules lexer))

(menhir
 (modules parser))

(executable
 (name main)
 (public_name garter)
 (modules main)
 (libraries garter_impl cmdliner))

(test
 (name test)
 (modules test)
 (libraries garter_impl))

(env
 (dev
  (flags
   (:standard -w +a-4-9-27-32-33-40-42-44-48-70))))
